server:
  grpc:
    host: 0.0.0.0
    port: 10400
  http:
    host: 0.0.0.0
    port: 10080
event:
  grpc:
    host: 0.0.0.0
    port: 20400
  http:
    host: 0.0.0.0
    port: 20080

log:
  level: debug #  debug, info, warn, error, dpanic, panic, fatal
  mode: production # development, production
  encoding: json # console, json
  stacktrace_level: # value like level, can be empty
  masked_fields:
    - Password

mysql:
  host: localhost
  port: 3306
  database: sample
  username: root
  password: 1
  max_open_conns: 20
  max_idle_conns: 5
  options:
    - key: 'parseTime'
      value: 'true'
    - key: 'loc'
      value: 'Asia/Ho_Chi_Minh'
