server:
  grpc:
    host: 0.0.0.0
    port: 10400
  http:
    host: 0.0.0.0
    port: 10080

mysql:
  host: localhost
  port: 3306
  database: sample
  username: root
  password: 1
  max_open_conns: 20
  max_idle_conns: 5
  options:
    - key: 'parseTime'
      value: 'true'
    - key: 'loc'
      value: 'Asia/Ho_Chi_Minh'
